# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeFinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeFinder
pod "Alamofire"
pod "CryptoSwift", "1.3.1"
pod "RNCryptor", "5.1.0"
pod 'SnapKit', '~> 5.0'
pod 'lottie-ios'
end
