# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def sharedPods
    pod "Alamofire"
    pod "CryptoSwift", "1.3.1"
    pod "RNCryptor", "5.1.0"
    pod 'SnapKit', '~> 5.0'
    pod 'lottie-ios'
    pod 'Purchases', '3.4.0'
end
def sharedPodsWatch
  pod "Alamofire"
end
target 'RecipeFinder Watch Extension' do
platform :watchos, '5.0'
   sharedPodsWatch
end
target 'RecipeFinder' do
platform :ios, '9.0'
   sharedPods
end
